---
abstract: 'Mojolicious and Async MySQL'
author:
  - 'Jan Henning Thorsen <jhthorsen@cpan.org>'
build_requires:
  Test::More: 0.90
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojo-mysql
no_index:
  directory:
    - t
    - inc
requires:
  DBD::mysql: 0
  Mojolicious: 5.47
resources:
  bugtracker: https://github.com/jhthorsen/mojo-mysql/issues
  homepage: https://github.com/jhthorsen/mojo-mysql
  repository: https://github.com/jhthorsen/mojo-mysql.git
version: 0.01
